In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('BankChurners.xlsx')

In [3]:
df.head()

CLIENTNUM  Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383.0             1.0          45.0      M              3.0   
1  818770008.0             1.0          49.0      F              5.0   
2  713982108.0             1.0          51.0      M              3.0   
3  769911858.0             1.0          40.0      F              4.0   
4  709106358.0             1.0          40.0      M              3.0   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0            39.0                       5.0                     1.0   
1            44.0                       6.0                     1.0   
2            36.0                       4.0                     1.0   
3            34.0                       3.0                     4.0   
4            21.0                       5.0                     1.0   

   Credit_Limit  Total_Revolving_Bal  Total_Trans_Amt  Total_Trans_Ct  
0       12691.0                777.0           1144.0            42.0  
1        8256.0                864.0           1291.0            33.0  
2        3418.0                  0.0           1887.0            20.0  
3        3313.0               2517.0           1171.0            20.0  
4        4716.0                  0.0            816.0            28.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10127 non-null  float64
 1   Attrition_Flag            10127 non-null  float64
 2   Customer_Age              10127 non-null  float64
 3   Gender                    10127 non-null  object 
 4   Dependent_count           10127 non-null  float64
 5   Education_Level           10127 non-null  object 
 6   Marital_Status            10127 non-null  object 
 7   Income_Category           10127 non-null  object 
 8   Card_Category             10127 non-null  object 
 9   Months_on_book            10127 non-null  float64
 10  Total_Relationship_Count  10127 non-null  float64
 11  Months_Inactive_12_mon    10127 non-null  float64
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  float64
 14  Total_

In [5]:
bic_var = ['Gender','Education_Level','Marital_Status','Income_Category','Card_Category']

In [6]:
#LabelEncoder文字轉數字
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

for i in range(len(bic_var)):
  df[bic_var[i]]=labelencoder.fit_transform(df[bic_var[i]])
  print(labelencoder.classes_)
df.head()

['F' 'M']
['College' 'Doctorate' 'Graduate' 'High School' 'Post-Graduate'
 'Uneducated' 'Unknown']
['Divorced' 'Married' 'Single' 'Unknown']
['$120K +' '$40K - $60K' '$60K - $80K' '$80K - $120K' 'Less than $40K'
 'Unknown']
['Blue' 'Gold' 'Platinum' 'Silver']


CLIENTNUM  Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0  768805383.0             1.0          45.0       1              3.0   
1  818770008.0             1.0          49.0       0              5.0   
2  713982108.0             1.0          51.0       1              3.0   
3  769911858.0             1.0          40.0       0              4.0   
4  709106358.0             1.0          40.0       1              3.0   

   Education_Level  Marital_Status  Income_Category  Card_Category  \
0                3               1                2              0   
1                2               2                4              0   
2                2               1                3              0   
3                3               3                4              0   
4                5               1                2              0   

   Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0            39.0                       5.0                     1.0   
1            44.0                       6.0                     1.0   
2            36.0                       4.0                     1.0   
3            34.0                       3.0                     4.0   
4            21.0                       5.0                     1.0   

   Credit_Limit  Total_Revolving_Bal  Total_Trans_Amt  Total_Trans_Ct  
0       12691.0                777.0           1144.0            42.0  
1        8256.0                864.0           1291.0            33.0  
2        3418.0                  0.0           1887.0            20.0  
3        3313.0               2517.0           1171.0            20.0  
4        4716.0                  0.0            816.0            28.0

#卡方檢定

In [7]:
import scipy.stats as stats
blist=[]
pvlist=[]
for i in range(len(bic_var)):
 hh=pd.crosstab(df['Attrition_Flag'],df[bic_var[i]])
 cr=stats.chi2_contingency(hh)
 blist.append(cr[0])
 pvlist.append(cr[1])

In [8]:
pd.set_option('display.float_format',lambda x:'%.2f'%x)
result=pd.DataFrame(blist,bic_var,columns=['卡方值'])
result.insert(1,'pv',pvlist)
result

卡方值   pv
Gender          13.87 0.00
Education_Level 12.51 0.05
Marital_Status   6.06 0.11
Income_Category 12.83 0.03
Card_Category    2.23 0.53

#T檢定

In [9]:
fin_var=['Customer_Age','Dependent_count','Months_on_book','Total_Relationship_Count','Months_Inactive_12_mon','Credit_Limit','Total_Revolving_Bal','Total_Trans_Amt','Total_Trans_Ct']

In [10]:
from scipy import stats
name=[]
alist=[]
pvlist=[]
for i in range(len(fin_var)):
  (a,pv)=stats.ttest_ind(df[fin_var[i]][df['Attrition_Flag']==0],df[fin_var[i]][df['Attrition_Flag']==1])
  name.append(fin_var[i])
  alist.append(a)
  pvlist.append(pv)

In [11]:
pd.set_option('display.float_format',lambda x:'%.2f'%x)
result=pd.DataFrame(alist,name,columns=['t'])
result.insert(1,'pv',pvlist)
result

t   pv
Customer_Age               1.83 0.07
Dependent_count            1.91 0.06
Months_on_book             1.38 0.17
Total_Relationship_Count -15.27 0.00
Months_Inactive_12_mon    15.52 0.00
Credit_Limit              -2.40 0.02
Total_Revolving_Bal      -27.44 0.00
Total_Trans_Amt          -17.21 0.00
Total_Trans_Ct           -40.25 0.00

#決策樹

In [12]:
X=df[['Gender','Income_Category','Total_Relationship_Count','Months_Inactive_12_mon','Credit_Limit','Total_Revolving_Bal','Total_Trans_Amt','Total_Trans_Ct']]
y=df['Attrition_Flag']
from sklearn.model_selection import train_test_split #區分訓練集與測試集
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=20)

In [13]:
#以決策樹建立預測模型
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT= DT.fit(X, y)

In [14]:
print('特徵重要程度: ',DT.feature_importances_)

特徵重要程度:  [0.0154076  0.02159195 0.11084913 0.03384668 0.05864031 0.23485746
 0.20304826 0.32175861]


In [15]:
#評估決策樹訓練集預測結果的混淆矩陣/精準度、召回率、F1
DT_pred= DT.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,DT_pred))
print("======================================================\n")
print(classification_report(y_train,DT_pred))

[[1168    0]
 [   0 5920]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1168
         1.0       1.00      1.00      1.00      5920

    accuracy                           1.00      7088
   macro avg       1.00      1.00      1.00      7088
weighted avg       1.00      1.00      1.00      7088



In [16]:
#評估決策樹測試集預測結果的混淆矩陣/精準度、召回率、F1
DT_tpred= DT.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,DT_tpred))
print("======================================================\n")
print(classification_report(y_test,DT_tpred))

[[ 459    0]
 [   0 2580]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       459
         1.0       1.00      1.00      1.00      2580

    accuracy                           1.00      3039
   macro avg       1.00      1.00      1.00      3039
weighted avg       1.00      1.00      1.00      3039



In [17]:
import joblib
joblib.dump(DT, '持卡戶流失')

['持卡戶流失']

In [18]:
loaded_model = joblib.load('持卡戶流失')
result = loaded_model.predict(np.array([[0,0,0,0,3000.0,0.0,2000.0,25.0]]))
print(result)
#DT.predict([[0,0,0,0,3000.0,0.0,2000.0,25.0]])

[0.]


C:\Users\alice\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


#隨機森林

In [19]:
#使用隨機森林進行機器學習模型
from sklearn.ensemble import RandomForestClassifier

#n_estimator代表要最高使用多少棵樹
RF = RandomForestClassifier(n_estimators=55,random_state=60) #oob_score=True,

#從訓練組資料中建立隨機森林模型
RF.fit(X_train,y_train)

RandomForestClassifier(n_estimators=55, random_state=60)

In [20]:
#列出各特徵重要程度
print('特徵重要程度: ',RF.feature_importances_)
#print('oob score: ',RF.oob_score_)

特徵重要程度:  [0.01602461 0.02747386 0.09573013 0.04956759 0.09804132 0.17031099
 0.29747864 0.24537286]


In [21]:
#評估隨機森林訓練集預測結果的精準度、召回率、F1
RF_pred= RF.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,RF_pred))
print("======================================================\n")
print(classification_report(y_train,RF_pred))

[[1168    0]
 [   1 5919]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1168
         1.0       1.00      1.00      1.00      5920

    accuracy                           1.00      7088
   macro avg       1.00      1.00      1.00      7088
weighted avg       1.00      1.00      1.00      7088



In [22]:
#評估隨機森林測試集預測結果的精準度、召回率、F1
RF_tpred= RF.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,RF_tpred))
print("======================================================\n")
print(classification_report(y_test,RF_tpred))

[[ 361   98]
 [  56 2524]]

              precision    recall  f1-score   support

         0.0       0.87      0.79      0.82       459
         1.0       0.96      0.98      0.97      2580

    accuracy                           0.95      3039
   macro avg       0.91      0.88      0.90      3039
weighted avg       0.95      0.95      0.95      3039



# 羅吉斯回歸

In [23]:
#利用邏輯斯迴歸分析建立預測模式
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X, y)

LogisticRegression()

In [24]:
#計算正確率、精準度、召回率及綜合指標f1(train訓練集)
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[ 401  767]
 [ 160 5760]]

              precision    recall  f1-score   support

         0.0       0.71      0.34      0.46      1168
         1.0       0.88      0.97      0.93      5920

    accuracy                           0.87      7088
   macro avg       0.80      0.66      0.69      7088
weighted avg       0.85      0.87      0.85      7088



In [25]:
#計算正確率、精準度、召回率及綜合指標f1(test測試集)
from sklearn.metrics import classification_report,confusion_matrix
LR_tpred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_tpred))
print("======================================================\n")
print(classification_report(y_test,LR_tpred))

[[ 145  314]
 [  69 2511]]

              precision    recall  f1-score   support

         0.0       0.68      0.32      0.43       459
         1.0       0.89      0.97      0.93      2580

    accuracy                           0.87      3039
   macro avg       0.78      0.64      0.68      3039
weighted avg       0.86      0.87      0.85      3039



# 判別分析

In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
LDA = LinearDiscriminantAnalysis()
LDA.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [27]:
#列印訓練完成之模式的混淆矩陣(confusion matrix)以及模式衡量指標
from sklearn.metrics import classification_report,confusion_matrix
LDA_pred= LDA.predict(X_train)
print(confusion_matrix(y_train,LDA_pred))
print("======================================================\n")
print(classification_report(y_train,LDA_pred))

[[ 598  570]
 [ 236 5684]]

              precision    recall  f1-score   support

         0.0       0.72      0.51      0.60      1168
         1.0       0.91      0.96      0.93      5920

    accuracy                           0.89      7088
   macro avg       0.81      0.74      0.77      7088
weighted avg       0.88      0.89      0.88      7088



In [28]:
#列印測試資料的混淆矩陣(confusion matrix)以及模式衡量指標
LDA_tpred= LDA.predict(X_test)
print(confusion_matrix(y_test,LDA_tpred))
print("======================================================\n")
print(classification_report(y_test,LDA_tpred))

[[ 232  227]
 [ 109 2471]]

              precision    recall  f1-score   support

         0.0       0.68      0.51      0.58       459
         1.0       0.92      0.96      0.94      2580

    accuracy                           0.89      3039
   macro avg       0.80      0.73      0.76      3039
weighted avg       0.88      0.89      0.88      3039



# SVM

In [35]:
from sklearn import svm 
clf = svm.SVC(kernel='rbf',C=1,gamma='auto') 
clf.fit(X_train,y_train)

SVC(C=1, gamma='auto')

In [36]:
#列印訓練完成之模式的混淆矩陣(confusion matrix)以及模式衡量指標
from sklearn.metrics import classification_report,confusion_matrix
clf_pred= clf.predict(X_train)
print(confusion_matrix(y_train,clf_pred))
print("======================================================\n")
print(classification_report(y_train,clf_pred))

[[1168    0]
 [   0 5920]]

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1168
         1.0       1.00      1.00      1.00      5920

    accuracy                           1.00      7088
   macro avg       1.00      1.00      1.00      7088
weighted avg       1.00      1.00      1.00      7088



In [37]:
clf_tpred= clf.predict(X_test)
print(confusion_matrix(y_test,clf_tpred))
print("======================================================\n")
print(classification_report(y_test,clf_tpred))

[[   0  459]
 [   0 2580]]

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       459
         1.0       0.85      1.00      0.92      2580

    accuracy                           0.85      3039
   macro avg       0.42      0.50      0.46      3039
weighted avg       0.72      0.85      0.78      3039



C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 類神經網路

In [29]:
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(20,10,2), random_state=50)
MLP.fit(X_train,y_train) 

MLPClassifier(hidden_layer_sizes=(20, 10, 2), random_state=50, solver='lbfgs')

In [30]:
MLP_pred= MLP.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,MLP_pred))
print("======================================================\n")
print(classification_report(y_train,MLP_pred))

[[   0 1168]
 [   0 5920]]

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      1168
         1.0       0.84      1.00      0.91      5920

    accuracy                           0.84      7088
   macro avg       0.42      0.50      0.46      7088
weighted avg       0.70      0.84      0.76      7088



C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
MLP_tpred= MLP.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,MLP_tpred))
print("======================================================\n")
print(classification_report(y_test,MLP_tpred))

[[   0  459]
 [   0 2580]]

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       459
         1.0       0.85      1.00      0.92      2580

    accuracy                           0.85      3039
   macro avg       0.42      0.50      0.46      3039
weighted avg       0.72      0.85      0.78      3039



C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alice\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# KNN 

In [32]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [33]:
KNN_pred= KNN.predict(X_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,KNN_pred))
print("======================================================\n")
print(classification_report(y_train,KNN_pred))

[[ 785  383]
 [ 205 5715]]

              precision    recall  f1-score   support

         0.0       0.79      0.67      0.73      1168
         1.0       0.94      0.97      0.95      5920

    accuracy                           0.92      7088
   macro avg       0.87      0.82      0.84      7088
weighted avg       0.91      0.92      0.91      7088



In [34]:
KNN_tpred= KNN.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,KNN_tpred))
print("======================================================\n")
print(classification_report(y_test,KNN_tpred))

[[ 260  199]
 [ 129 2451]]

              precision    recall  f1-score   support

         0.0       0.67      0.57      0.61       459
         1.0       0.92      0.95      0.94      2580

    accuracy                           0.89      3039
   macro avg       0.80      0.76      0.78      3039
weighted avg       0.89      0.89      0.89      3039

